// Optional LLM provider. When an API key is present in the environment,
// feedback is generated by a real model using the same JSON contract as the
// local analyzer. Without a key, server falls back to the local analyzer.

const SYSTEM_PROMPT = `You are Padhaaku, a Socratic study buddy. A learner is trying to understand a topic by explaining it in their own words (typed text or a mind map). Your job is to assess their understanding, encourage what is correct, gently flag misconceptions, point out missing pieces, and nudge them toward a better understanding. Be warm, concise, and never just hand them the full answer.

You MUST reply with ONLY a JSON object (no markdown) matching this TypeScript type:
{
  "score": number,            // 0-100, how complete/accurate their explanation is
  "summary": string,          // 1-2 sentence encouraging assessment
  "items": Array<{
    "kind": "good" | "incomplete" | "misconception" | "missing",
    "title": string,          // short label
    "detail": string,         // one sentence of guidance
    "nodeId": string | null,  // id of the mind-map node this refers to, if any
    "span": string | null     // an EXACT substring of the learner's text to highlight, if any
  }>,
  "followUp": string,         // one probing question to push their thinking
  "modelAnswer": string       // a short ideal explanation of the topic
}`;

function buildUserPrompt({ topic, mode, text, nodes }) {
  const nodeLines =
    nodes && nodes.length
      ? nodes.map((n) => `  - [${n.id}] ${n.text}`).join("\n")
      : "  (none)";
  return `Topic the learner is studying: "${topic}"
Input mode: ${mode}
Their explanation (free text):
"""
${text || "(empty)"}
"""
Mind-map nodes (id -> text), reference these ids in "nodeId" when relevant:
${nodeLines}

Assess their understanding and respond with the JSON object only.`;
}

function safeParse(content) {
  if (!content) return null;
  let txt = content.trim();
  // Strip markdown code fences if present.
  txt = txt.replace(/^```(?:json)?/i, "").replace(/```$/i, "").trim();
  const start = txt.indexOf("{");
  const end = txt.lastIndexOf("}");
  if (start === -1 || end === -1) return null;
  try {
    return JSON.parse(txt.slice(start, end + 1));
  } catch {
    return null;
  }
}

async function callOpenAI(payload, apiKey) {
  const res = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: process.env.OPENAI_MODEL || "gpt-4o-mini",
      temperature: 0.4,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: buildUserPrompt(payload) },
      ],
    }),
  });
  if (!res.ok) throw new Error(`OpenAI ${res.status}: ${await res.text()}`);
  const data = await res.json();
  return safeParse(data.choices?.[0]?.message?.content);
}

async function callAnthropic(payload, apiKey) {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: process.env.ANTHROPIC_MODEL || "claude-3-5-haiku-latest",
      max_tokens: 1024,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: buildUserPrompt(payload) }],
    }),
  });
  if (!res.ok) throw new Error(`Anthropic ${res.status}: ${await res.text()}`);
  const data = await res.json();
  return safeParse(data.content?.[0]?.text);
}

export function hasLLM() {
  return Boolean(process.env.OPENAI_API_KEY || process.env.ANTHROPIC_API_KEY);
}

export async function analyzeWithLLM(payload) {
  let parsed = null;
  let provider = null;
  if (process.env.OPENAI_API_KEY) {
    parsed = await callOpenAI(payload, process.env.OPENAI_API_KEY);
    provider = "openai";
  } else if (process.env.ANTHROPIC_API_KEY) {
    parsed = await callAnthropic(payload, process.env.ANTHROPIC_API_KEY);
    provider = "anthropic";
  }
  if (!parsed) return null;

  return {
    provider,
    topicLabel: payload.topic,
    score: clampScore(parsed.score),
    summary: String(parsed.summary || ""),
    items: Array.isArray(parsed.items)
      ? parsed.items.map((i) => ({
          kind: ["good", "incomplete", "misconception", "missing"].includes(i.kind)
            ? i.kind
            : "incomplete",
          title: String(i.title || ""),
          detail: String(i.detail || ""),
          nodeId: i.nodeId ? String(i.nodeId) : null,
          span: i.span ? String(i.span) : null,
        }))
      : [],
    followUp: String(parsed.followUp || ""),
    modelAnswer: String(parsed.modelAnswer || ""),
  };
}

function clampScore(n) {
  const v = Number(n);
  if (Number.isNaN(v)) return 0;
  return Math.max(0, Math.min(100, Math.round(v)));
}
